echo "hello world !"
echo "first test for push trigger Jenkins build..."
echo "second test for push trigger Jenkins build..."
echo "third test for push trigger Jenkins build..."
echo "fourth test for push trigger Jenkins build..."
echo "fifth test for push trigger Jenkins build..."
echo "error"
echo "warning"
echo "Warning"
echo "WARNING"
#error
