echo "hello world !"
echo "first test for push trigger Jenkins build..."
echo "second test for push trigger Jenkins build..."
echo "BUILD"
echo "INFO: third test for push trigger Jenkins build..."
echo "fourth test for push trigger Jenkins build..."
echo "fifth test for push trigger Jenkins build..."
echo "error: run regression is failure"
echo "run regression is error"
echo "this is a warning"
echo "Warning is here"
echo "BUILD"
echo "WARNING"
#error  #Jenkins build only detect the last statement. Build will be success if no line 14(error).
echo "test is complete"
#error
